[reno]
"ruta nombres" = "T:/TAG/EJECUTABLES/RECURSOS/pro_plex/modelos"
"ruta json" = "./nombres.json"
"formato imgs" = ["jpg", "png", "gif"]
"sep nombres" = ", "
"motores" = ["MediaInfo", "Mp4Info", "ExifTool", "FFmpeg"]
"motor elegido" = 0
"plantilla" = "[$duracion$ $bitratev$ $tags$]-$alto$p"
"w" = 720
"h" = 340
