[parametros]
video = [
        'Width',
        'Height',
        'DisplayAspectRatio/String',
        'BitRate',
        'BitRate/String',
        'FrameRate',
        'FrameRate/String',
        'FrameCount',
        'StreamSize',
        'StreamSize/String',
        'CodecID/Info',
        'Format',
        'Format_Profile',
        'Duration',
        'Duration/String1',
        'Duration/String3',
        'InternetMediaType',
        'CodecID',
        'CodecID/Info'
        ]
audio = [
        'Format',
        'Format/String',
        'Format/Info',
        'Format_Commercial',
        'CodecID',
        'Duration',
        'Duration/String',
        'BitRate',
        'BitRate/String',
        'Channel(s)/String',
        'SamplingRate',
        'SamplingRate/String',
        'SamplingCount',
        'FrameRate',
        'FrameRate/String',
        'Compression_Mode',
        'StreamSize',
        'StreamSize/String'
        ]
general = [
        'FileSize',
        'FileSize/String',
        'Duration',
        'FileName',
        'Duration/String',
        'Duration/String1',
        'Duration/String2',
        'Duration/String3',
        'Duration/String4',
        'Duration/String5',
        'BitRate',
        'BitRate/String',
        'FrameRate',
        'FrameRate/String',
        'CompleteName',
        'FolderName',
        'FileNameExtension',
        'FileName',
        'FileExtension',
        'Format',
        'InternetMediaType',
        'CodecID',
        'CodecID/String',
        'Title',
        'Season',
        'Movie',
        'Album',
        'Part',
        'Track',
        'Chapter',
        'Performer',
        'Composer',
        'Conductor',
        'Director',
        'Actor',
        'Producer',
        'Genre',
        'Description',
        'Keywords',
        'Summary',
        'Synopsis',
        'Encoded_Date',
        'Tagged_Date',
        'File_Created_Date',
        'File_Created_Date_Local',
        'File_Modified_Date',
        'File_Modified_Date_Local',
        'Cover',
        'Cover_Description',
        'Cover_Type',
        'Cover_Mime',
        'Cover_Data',
        'Lyrics',
        'Comment',
        'Rating',
        'Played_Count',
        'Encoded_Application',
        'Encoded_Application/String'
        ]
menu = [
        'Count',
        'Status',
        'StreamCount',
        'StreamKind',
        'StreamKind/String',
        'StreamKindID',
        'StreamKindPos',
        'StreamOrder',
        'FirstPacketOrder',
        'Inform',
        'ID',
        'ID/String',
        'OriginalSourceMedium_ID',
        'OriginalSourceMedium_ID/String',
        'UniqueID',
        'UniqueID/String',
        'MenuID',
        'MenuID/String',
        'Format',
        'Format/String',
        'Format/Info',
        'Format/Url',
        'Format_Commercial',
        'Format_Commercial_IfAny',
        'Format_Version',
        'Format_Profile',
        'Format_Compression',
        'Format_Settings',
        'Format_AdditionalFeatures',
        'CodecID',
        'CodecID/String',
        'CodecID/Info',
        'CodecID/Hint',
        'CodecID/Url',
        'CodecID_Description',
        'Codec',
        'Codec/String',
        'Codec/Info',
        'Codec/Url',
        'Duration',
        'Duration/String',
        'Duration/String1',
        'Duration/String2',
        'Duration/String3',
        'Duration/String4',
        'Duration/String5',
        'Duration_Start',
        'Duration_End',
        'Delay',
        'Delay/String',
        'Delay/String1',
        'Delay/String2',
        'Delay/String3',
        'Delay/String4',
        'Delay/String5',
        'Delay_Settings',
        'Delay_DropFrame',
        'Delay_Source',
        'FrameRate_Mode',
        'FrameRate_Mode/String',
        'FrameRate',
        'FrameRate/String',
        'FrameRate_Num',
        'FrameRate_Den',
        'FrameCount',
        'List_StreamKind',
        'List_StreamPos',
        'List',
        'List/String',
        'Title',
        'Language',
        'Language/String',
        'Language/String1',
        'Language/String2',
        'Language/String3',
        'Language/String4',
        'Language_More',
        'ServiceKind',
        'ServiceKind/String',
        'ServiceName',
        'ServiceChannel',
        'Service/Url',
        'ServiceProvider',
        'ServiceProvider/Url',
        'ServiceType',
        'NetworkName',
        'Original/NetworkName',
        'Countries',
        'TimeZones',
        'LawRating',
        'LawRating_Reason',
        'Disabled',
        'Disabled/String',
        'Default',
        'Default/String',
        'Forced',
        'Forced/String',
        'AlternateGroup',
        'AlternateGroup/String',
        'Chapters_Pos_Begin',
        'Chapters_Pos_End'
        ]

[basico]
pesoi = ['FileSize', 'general']
"tiempo texto" = ['Duration/String2', 'general']
bitrate = ['BitRate/String', 'general']
aspecto = ['DisplayAspectRatio/String', 'video']
bitratev = ['BitRate/String', 'video']
ancho = ['Width', 'video']
alto = ['Height', 'video']
codec = ['CodecID', 'video']
fps = ['FrameRate', 'video']
"duracion ms" = ['Duration', 'video']
tiempo = ['Duration/String3', 'video']

[config]
" min " = "."
" " = ""
"/" = "p"
":" = ""

[otros]