[config]
ffprobe = "ffprobe.exe"
"cmd info" = "-v error -show_format -show_streams -print_format json"

# FORMAT - GENERAL
[raw]
format = [
    "bit_rate",
    "duration",
    "nb_streams",
    "size",
    "filename",
]
tags = [
    "artist",
    "category",
    "description",
    "genre",
    "keywords",
    "synopsis",
    "title"
]
# FORMAT - GENERAL
# VIDEO
video = [
    "bit_rate",
    "codec_long_name",
    "codec_name",
    "codec_tag_string",
    "codec_type",
    "coded_height",
    "coded_width",
    "display_aspect_ratio",
    "duration",
    "duration_ts",
    "height",
    "width",
]
# VIDEO
audio = [
    "bit_rate",
    "codec_long_name",
    "codec_name",
    "codec_tag_string",
    "codec_type",
    "duration",
    "duration_ts",
    "sample_rate",
    "time_base",
    "profile",
]